/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HoudiniDisplay {
  variants: HoudiniVariantDisplay[];
  labels: HoudiniLabelDisplay[];
  sustainability_icons: HoudiniSustainabilityIcons[];
  description: string;
  /**
   * Unique identifier of the product.
   */
  product_id: string;
  /**
   * Product title
   */
  title: string;
  /**
   * Original price if the product is on sale.
   */
  original_price: number;
  /**
   * The price the product is currently sold for.
   */
  sale_price: number;
  /**
   * URL to the product page
   */
  page_url: string;
  /**
   * Main image of the product
   */
  image_url: string;
  /**
   * Whether the product is in stock or not.
   */
  in_stock: boolean;
  recommendation_id: string;
}
export interface HoudiniVariantDisplay {
  id: string;
  image_urls: string[];
  sizes: HoudiniSizeDisplay[];
  color_name: string;
  color_hex: string;
  color_filter: string;
  this_variant: boolean;
  [k: string]: unknown;
}
export interface HoudiniSizeDisplay {
  title: string;
  in_stock: boolean;
  original_price: number;
  sale_price: number;
  [k: string]: unknown;
}
export interface HoudiniLabelDisplay {
  color?: string;
  title: string;
  [k: string]: unknown;
}
export interface HoudiniSustainabilityIcons {
  id: string;
  title: string;
  [k: string]: unknown;
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StrongerDisplay {
  product_type?: string;
  product_types: {
    [k: string]: string;
  };
  hover_image_url: string;
  sku: string;
  sale_prices: {
    [k: string]: number;
  };
  original_prices: {
    [k: string]: number;
  };
  currency: string;
  sizes: string[];
  sizes_in_stock: {
    [k: string]: string[];
  };
  badges: string[];
  /**
   * Unique identifier of the product.
   */
  product_id: string;
  /**
   * Product title
   */
  title: string;
  /**
   * Original price if the product is on sale.
   */
  original_price: number;
  /**
   * The price the product is currently sold for.
   */
  sale_price: number;
  /**
   * URL to the product page
   */
  page_url: string;
  /**
   * Main image of the product
   */
  image_url: string;
  /**
   * Whether the product is in stock or not.
   */
  in_stock: boolean;
  recommendation_id: string;
}

export interface SpendrupsDisplay {
  /**
   * All variants of the product. The variant matching the product_id of the root should be pre-selected.
   */
  variants: SpendrupsVariant[];
  /**
   * Internal Depict use only, always true for Spendrups
   */
  in_stock: boolean;
  /**
   * Unique identifier of the product.
   */
  product_id: string;
  recommendation_id: string;
}
export interface SpendrupsVariant {
  /**
   * If the product_id matches the root level, this variant should be pre-selected
   */
  product_id: string;
  image_url?: string;
  page_url: string;
  title: string;
  variant_name: string;
  list_price: number;
  list_price_per_unit: number;
  units_per_base_unit: number;
  country?: string;
  /**
   * A list of tags to display on the product card.
   */
  tags: SpendrupsTag[];
  seller_only: boolean;
  accessory_pot_item: boolean;
  limited: boolean;
  in_stock: boolean;
}
export interface SpendrupsTag {
  /**
   * The text to display on the tag
   */
  text: string;
  /**
   * A CSS class name defined by Spendrup's stylesheets, specifying the color of the tag
   */
  class: string;
}


export interface MayaDelorezDisplay {
  variant_index: number;
  variant_displays: MayaDelorezVariant[];
  recommendation_id?: string;
  search_result_id?: string;
  product_listing_result_id?: string;
}
​
export interface MayaDelorezVariant {
  title:                  string;
  original_price:         number;
  in_stock:               boolean;
  sale_price:             number;
  page_url:               string;
  display_item_id:        string;
  product_id:             string;
  transaction_product_id: string;
  item_group_id:          string;
  image_urls:             string[];
}