/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContentSearchRequestV2 {
  tenant: string;
  market: string;
  /**
   * The locale to use for the search. If not set, the default locale will be used.
   */
  locale?: string;
  /**
   * The search query.
   */
  query?: string;
  user_id?: string;
  session_id?: string;
  dsid?: string;
}
