/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContentSearchResponse {
  content_request_id: string;
  /**
   * List of links to content pages that match the search query.
   */
  links: ContentLink[];
}
export interface ContentLink {
  type?: "content_link";
  /**
   * Title for the content page
   */
  title: string;
  /**
   * Short human-readable description for the content page
   */
  description: string;
  /**
   * URL for the content page image
   */
  image_url?: string;
  /**
   * URL for the content page
   */
  page_url: string;
  /**
   * Highlights that show why the search query matched this content page
   */
  highlights?: TypesenseHighlights[];
}
export interface TypesenseHighlights {
  field: string;
  snippet: string;
  matched_tokens: string[];
}
