/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CollectionType =
  | "long_tail_collection"
  | "campaign"
  | "category"
  | "smart_pick"
  | "style"
  | "brand"
  | "look";

export interface FeaturedInRequestV3 {
  merchant: string;
  market: string;
  locale: string;
  product_id: string;
  collection_type: CollectionType;
}
