/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CollectionType =
  | "long_tail_collection"
  | "campaign"
  | "category"
  | "smart_pick"
  | "style"
  | "brand"
  | "look";

export interface FeaturedInResponseV3 {
  listings: FeaturedInDisplay[];
}
export interface FeaturedInDisplay {
  /**
   * Depict ID of the listing.
   */
  listing_id: string;
  /**
   * ID of the listing in the merchant PIM, CMS or similar.
   */
  external_id?: string;
  listing_type: CollectionType;
  /**
   * Show or hide this listing in navigation breadcrumbs.
   */
  show_in_breadcrumbs: boolean;
  /**
   * Show or hide this listing in quicklinks.
   */
  show_in_quicklinks: boolean;
  /**
   * List of image URLs for the listing.
   */
  image_urls: string[];
  title: string;
  slug?: string;
  displays: MinimalDisplay[];
}
export interface MinimalDisplay {
  variant_index: number;
  variant_displays: MinimalVariantDisplay[];
  recommendation_id?: string;
  search_result_id?: string;
  product_listing_result_id?: string;
}
export interface MinimalVariantDisplay {
  product_id: string;
  title: string;
  image_urls: string[];
  original_price: number;
  sale_price: number;
  in_stock: boolean;
  [k: string]: unknown;
}
