/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetDisplaysRequestV2 {
  /**
   * Market identifier
   */
  market: string;
  /**
   * @minItems 1
   * @maxItems 50
   */
  product_ids: [string, ...string[]];
  /**
   * Identifier associated with the API integration
   */
  tenant: string;
}
