/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This class is just used to document the query parameters for frontend. It is not used in the backend.
 * Backend: def get_listing_endpoint
 */
export interface GetListingRequest {
  listing_id: string;
  merchant: string;
  market: string;
  locale: string;
}
