/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CollectionType =
  | "long_tail_collection"
  | "campaign"
  | "category"
  | "smart_pick"
  | "style"
  | "brand"
  | "look";

/**
 * This class is just used to document the query parameters for frontend. It is not used in the backend.
 * Backend: def listings_endpoint
 */
export interface ListListingsRequest {
  merchant: string;
  market: string;
  locale: string;
  types?: CollectionType[];
}
