/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListListingsResponseItem = ListListingsResponseItem1;
export type CollectionType =
  | "long_tail_collection"
  | "campaign"
  | "category"
  | "smart_pick"
  | "style"
  | "brand"
  | "look";

export interface ListListingsResponseItem1 {
  /**
   * Depict ID of the listing.
   */
  listing_id: string;
  /**
   * ID of the listing in the merchant PIM, CMS or similar.
   */
  external_id?: string;
  listing_type: CollectionType;
  /**
   * Show or hide this listing in navigation breadcrumbs.
   */
  show_in_breadcrumbs: boolean;
  /**
   * Show or hide this listing in quicklinks.
   */
  show_in_quicklinks: boolean;
  /**
   * List of image URLs for the listing.
   */
  image_urls: string[];
  title: string;
  slug?: string;
  children: ListListingsResponseItem1[];
}
