/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The type of query. By default, the endpoint will return query_ids for all types.
 */
export type ProductListingType = "category" | "collection" | "scollection";

export interface ProductListingQueriesRequest {
  tenant: string;
  market: string;
  /**
   * The locale to use for the search. If not set, the default locale will be used.
   */
  locale?: string;
  metadata?: {
    [k: string]: string;
  };
  type?: ProductListingType;
}
