/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VariantIndex = number;
export type VariantDisplays = {
  [k: string]: unknown;
}[];

export interface RecommendResponseV3 {
  displays: APIDisplay[];
  error?: string;
}
export interface APIDisplay {
  variant_index: VariantIndex;
  variant_displays: VariantDisplays;
  [k: string]: unknown;
}
