/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RecommendRequestV3 {
  /**
   * Identifier associated with the API integration
   */
  merchant: string;
  /**
   * Market identifier
   */
  market: string;
  /**
   * Locale identifier
   */
  locale: string;
  /**
   * Type of the recommendation, e.g. `cross_sell`
   */
  type: string;
  /**
   * Zero, one, or multiple product identifiers (depending on the id)
   */
  product_ids?: string[];
  /**
   * Maximum number of recommendations returned.
   */
  limit?: number;
  /**
   * Session identifier
   */
  session_id?: string;
}
