/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Request model for the search suggestions endpoint.
 */
export interface SearchSuggestionsRequestV3 {
  merchant: string;
  market: string;
  /**
   * The locale to use for the search
   */
  locale: string;
  /**
   * The query to search for.
   */
  query?: string;
  session_id?: string;
  /**
   * Maximum number of category suggestions to return. Defaults to 3.
   */
  limit?: number;
}
