#!/bin/bash

set -e

# Function to build a storefront
build_storefront() {
  local storefront=$1
  echo "Building storefront $storefront..."
  echo "node version"
  node --version

  # Updating the directory structure here
  cd ../storefronts/$storefront

  rm -rf .parcel-cache

  if [[ $storefront == "react-web" ]]; then
    echo "Running custom build command for react-web..."
    yarn build src/index.html && mv dist/index.html dist/404.html
  elif [[ -f "pnpm-lock.yaml" ]]; then
    echo "Building store, current CWD" $PWD
    pnpm build
  elif [[ -f "yarn.lock" ]]; then
    yarn build
  fi

  cd ../../browser-tags-v2
}

# Main script
storefronts=("next-commerce" "next-web" "react-web" "vanilla-js")

if [[ $1 == "--only-"* ]]; then
  only_storefront="${1:7}"
  build_storefront $only_storefront
else
  for storefront in "${storefronts[@]}"; do
    build_storefront $storefront
  done
fi
