/* tslint:disable */
export type HoudiniDisplay = {
  variant_index: number;
  variant_displays: HoudiniVariantDisplay[];
} & ({ search_result_id: string } | { product_listing_result_id: string } | { recommendation_id: string });

export interface HoudiniVariantDisplay {
  specific_color_name: string;
  labels: Label[];
  title: string;
  sustainability_icons: SustainabilityIcon[];
  color_name: string;
  description: string;
  in_stock: boolean;
  original_price: number;
  sale_price: number;
  page_url: string;
  size: string;
  product_id: string;
  product_query_id: string;
  transaction_product_id: string;
  item_group_id: string;
  image_urls: string[];
  color_hex: string;
  color_variant_id: string;
}

interface Label {
  id: string;
  title: string;
  color?: string;
}

interface SustainabilityIcon {
  id: string;
  title: string;
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StrongerDisplay extends SearchResult, ProductListingResult, Recommendation {
  variant_index: number;
  variant_displays: StrongerVariantDisplay[];
  search_result_id: string;
}

export interface StrongerVariantDisplay {
  badge?: Badge;
  title: string;
  product_type: string;
  in_stock: boolean;
  original_price: number;
  sale_price: number;
  currency: Currency;
  product_id: string;
  hover_image_url: string;
  image_urls: string[];
  item_group_id: string;
  handle: string;
  size: Size;
  transaction_product_id: string;
  sku: string;
}

type Badge = "NYHET" | "TRENDAR" | "RECYCLED";

type Currency = "SEK";

type Size = "Onesize" | "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXS";

interface SearchResult {
  search_result_id: string;
}

interface ProductListingResult {
  product_listing_result_id: string;
}

interface Recommendation {
  recommendation_id: string;
}
