/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StrongerDisplay extends SearchResult, ProductListingResult, Recommendation {
  variant_index: number;
  variant_displays: StrongerVariantDisplay[];
  search_result_id: string;
}

export interface StrongerVariantDisplay {
  badge?: Badge;
  title: string;
  product_type: string;
  in_stock: boolean;
  original_price: number;
  sale_price: number;
  currency: Currency;
  product_id: string;
  hover_image_url: string;
  image_urls: string[];
  item_group_id: string;
  handle: string;
  size: Size;
  transaction_product_id: string;
  sku: string;
}

type Badge = "NYHET" | "TRENDAR" | "RECYCLED";

type Currency = "SEK";

type Size = "Onesize" | "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXS";

interface SearchResult {
  search_result_id: string;
}

interface ProductListingResult {
  product_listing_result_id: string;
}

interface Recommendation {
  recommendation_id: string;
}


interface EquestrianVariant {
  product_id: string;
  transaction_product_id: string;
  item_group_id: string;
  page_url: string;
  title: string;
  /**
   * Original price if the product is on sale.
   */
  original_price: number;
  /**
   * The price the product is currently sold for.
   */
  sale_price: number;
  image_urls: string[];
  in_stock: boolean;
}
export interface EquestrianDisplay {
  /**
   * The index of the variant to be displayed.
   */
  variant_index: number;
  /**
   * All variant displays (eg. different colors, sizes) of the product.
   */
  variant_displays: EquestrianVariant[];
  /** Unique recommendation ID, for tracking use */
  recommendation_id: string;
}
